### ISSUE TITLE
Hot reloading does not work on Noopfile changes

### ISSUE THREAD

**Issue by varmamahesh** [noop-cloud/noop-local#9]
After an app is running locally using noop cli, any changes to Noopfiles do not reflect via hot reloading.

**Comment by mwkaufman** [comment]
rahul
noop-local - when i make changes in the Noopfile (like add an ENV variable) it doesnt reflect in the restart. It doesnt show in the inspector either. I end up doing a restart. Is this expected ? (edited) 

michael  < 1 minute ago
Yes, this is a known issue. When changing the Noopfile itself, exit and rerun "noop run". https://github.com/noop-cloud/noop-local/issues/9 It restarts because a file changed in the directory it was watching, but it doesn't know what file specifically.

**Comment by derekwolpert** [comment]
Addressed in https://github.com/noop-cloud/noop-local/pull/53 and https://github.com/noop-cloud/noop-discovery/pull/6
